version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: radar_saude
      POSTGRES_PASSWORD: saude_radar
      POSTGRES_DB: radar_saude
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U radar_saude"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: ["postgres", "-c", "max_connections=300"]

  backend:
    build:
      context: ./person-management-backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/radar_saude
      SPRING_DATASOURCE_USERNAME: radar_saude
      SPRING_DATASOURCE_PASSWORD: saude_radar
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./person-management-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://backend:8080
    depends_on:
      - backend

volumes:
  postgres_data: